# Introduction

About 30% of the earth surface is covered by forests and they have a significant importance for water and carbon cycles [@laurent2011inversion]. As forest environments are being threatened more and more, there is an increased concern for forest conservation [@grammatikopoulou2021value]. The effects of climate change on many different ecosystems have been studied and shown [@esquivel2019compositional]. Forest ecosystems are particularly more sensitive to climate change compared to other ecosystems [@esquivel2019compositional, @lindner2010climate]. According to @lindner2010climate, the main reason why forest ecosystems are exceptionally sensitive to unusual changes in climate is that compared to other organisms, most trees usually live longer and they have relatively less adaptive skills to respond to the rapid changes in the environment. 

Another threat to forest that has been increasingly reported during the last century is insect disturbances. Insect disturbances have increased the concern on forest species diversity, biogeochemical cycle and economic value of forest ecosytems [@senf2017remote]. Main forest insects that are responsible for many outbreaks can be divided into bark beetles and defoliators. Many bark beetle species can reproduce their offspring within both dead and living tree organisms' phloem. These bark beetles can easily destroy the structure of translocation processes (e.g. water and nutrient translocations) by introducing various pathogens (e.g. fungal) in healthy trees [@senf2017remote].

Study by @kautz2017biotic has reported that there is only a limited amount of consistent data for studying forest disturbance caused by insects [@senf2017remote]. Remote sensing images provide very interesting insights to study environmental disturbances and changes within forest areas. According to the study by @lechner2020applications, remote sensing techniques have recently been actively used for forest studies. For example, remote sensing images are offering important opportunities to map ecosystem distribution, to study forest plant productivity and get insights about the 3D structural properties of forest plants [@lechner2020applications]. 

One of the most important insights remote sensing provides is the fact that the image of earth's surface can be acquired over the time. This gives a unique opportunity of being able to study environmental changes on a specific area of interest over the time period the images are acquired. For example, there have been studies where remote sensing techniques were used to map the distribution of invasive species and to monitor land changes (e.g. forest habitat fragmentation) in forests [@lechner2020applications].

Another interesting opportunity that remote sensing data provide is to estimate vegetation biophysical and biochemical properties from remotely sensed images. Essentially, there are various ways to retrieve plant biophysical parameters from remote sensing data. Each method has its own advantages and disadvantages. Radiative transfer model (RTM) has been accepted to be the superior method to all the available techniques [@darvishzadeh2019analysis; @wang2018mapping]. Various RTMs have been proposed at different scales such as leaf and canopy scales. Different RTMs such as leaf and canopy can be used in a coupled mode in order to simulate canopy reflectance based on vegetation biophysical and biochemical properties [@morcillo2019quantifying].

There are mainly three inversion methods to estimate plant traits from remote sensing data. These methods are numerical optimization, look-up-table and hybrid techniques. Numerical optimization is considered to be a classical method. However, the major drawbacks of this method are its computational inefficiency and high risk of poor convergence [@zhang2021analyzing]. LUT method refers to a technique where databases to store simulated data is created by RTMs. And then, plant biophysical variables of the simulated reflectance that represents the measured data most closely are chosen as retrievals. Although the LUT method is more efficient than the classic numerical optimization, it is still a computationally inefficient process given that inversion needs to be done for each pixel in the remote sensing product [@danner2021efficient]. The hybrid method can be used to overcome the challenges of these less efficient techniques. In a typical hybrid method a regression model is combined with RTMs [@zhang2021analyzing].

Invertable Forest Reflectance Model (INFORM) is a combination of three RTMs (leaf and canopy) that can be used to simulate forest canopy reflectance in terms of canopy biophysical and biochemical parameters [@atzberger2000development; @schlerf2006inversion]. INFORM and machine learning models can be combined using a hybrid method to retrieve plant traits. The objective of this study is to review the hybrid methods that are used for retrieval of plant biophysical and biochemical variables. This study specifically focuses on a hybrid combination of INFORM and a machine learning model.

The main objectives of this study are to:

1. use the INFORM RTM to simulate canopy reflectance within the national park Hunsrück-Hochwald based on PRISMA data bands
2. train ANN using the simulated data in order to assess whether the relationship between plant traits and spectral data can be efficiently learned
2. assess whether ANN can deal with collinearity available in the hyperspectral data PRISMA
4. retrieve forest biophysical and biochemical maps for the study area Hunsrück-Hochwald


