# Forest Disturbances by Bark Beetle

Insect disturbance is one of the many natural disturbances forests experience. Insect outbreaks can have very important impacts on the ecosystem functioning [@raffa2009literal]. However, there have been concerns about these forest disturbances as severity and frequency of these disturbances have increased [@millar2015temperate].

One of the major insect contributors to European forest disturbances is called the European spruce bark beetle (*Ips typographus*). These bark beetles have been increasingly destroying European forests. These pest organisms specifically affects Norway spruce forests, as *Ips typographus*s are major pests of Norway spruce trees [@ohrn2014seasonal]. Temperature has a significant effect on the successful swarm of *Ips typographus*. The temperature of 16.5$^\circ$ is considered to be the minimum temperature (lower threshold) for the bark beetle to swarm and attack the trees. The length of the warm days is another factor increasing the chance of successful attack by the bark beetle. the European spruce trees have a defence mechanism to fight against the mass beetle outbreak. However, when there are at least three warm days in a row with a temperature well-above the swarming threshold of *Ips typographus*, then the likelihood of these pest organisms successfully overcoming the defense mechanism of the trees and infesting them are higher [@wermelinger2004ecology].

Once a tree is infested, there are typically three stages that the tree will go through. These stages are called the green attack, red attack and gray attack stages [@sprintsin2011combining]. The green attack stage is the first stage and it refers to a stage where usually the leaves of the infested trees are still green. In this stage, it is difficult to distinguish the infested trees at the canopy level [@wulder2006estimating]. During the green attack stage the infested tree may still be alive, but once this stage has started the death of the infested tree is inevitable. Moreover, during this stage the freshly hatched generation of the bark beetle uses the inner bark of the tree to grow and develop [@niemann2005assessment]. The next stage is called the red attack stage. During this phase, the leaves of the infested trees slowly turn to yellow and eventually becomes reddish [@fernandez2020monitoring]. The red attack stage occurs within the next year (one year) after the bark beetles perform a mass attack [@niemann2005assessment]. The final stage is the gray attack stage that refers to a stage where the trees have already shed the leaves [@wulder2009challenges]. At this point the infested trees are completely dead and abandoned by the new generation of the bark beetle [@niemann2005assessment]. During the final stage typically only the gray bark of the tree is left. Hence, this stage is called gray stage [@abdullah2019sensitivity]

Bark beetles are known to have a mutual (symbiotic) relationship with many different fungi species (e.g. *Ceratocystis spp*). These fungi species can easily infect trees. Sapwood and phloem of the trees are specifically effected by these species [@niemann2005assessment; @six2003genetic]. Once the trees are infected by the fungi carried by bark beetles, these fungi will start to disrupt the translocation of water and important nutrients in the infected tree [@paine1997interactions; @wermelinger2004ecology]. These are potentially causing changes in both biophysical and biochemical properties at canopy and leaf level [@abdullah2018european].

There are several factors that help *Ips typographus* to attack trees successfully. One of the major contributors to this process is thought to be climate change. Typically, when bark beetles exist at natural and low densities they cannot overcome the defense mechanism of the trees. However, climate change is favoring these beetles in many ways for their succesful attack. For example, increased length and number of warm and very dry days increase the likelyhood of mass bark beetle outbreak significantly. Specifically, these factors trigger beetle attacks in two ways: directly (e.g. increased insect population) and indirectly (e.g. weakened tree defence mechanisms against bark beetle) [@bale2002herbivory; @bentz2015modeling; @marini2017climate].

Effective forest management and early intervention is essential in order to deal with bark beetle outbreaks. Especially, detecting the infested trees while they are still going through the green attack stage is essential, because, at this point the beetles have not yet left the tree to look for new host trees. One of the traditional ways to identify and assess infested trees is manual field surveys. Typically these surveys are performed by foresters who try to look for sawdust within the bark of the trees. However, this method is extremely difficult, time-consuming and require many labors to study large forest areas. The field of remote sensing, however, offers methods to more effectively detect and map forest infestations [@abdullah2019sentinel; @immitzer2014early]. 

@immitzer2014early used World-View-2 data in order to study and detect bark beetle infestation during the green attack stage. In this study forest infestation map was produced using a machine learning method. Study by @ortiz2013early used RapidEye and TerraSAR-X data for early detection of bark beetle. This study demonstrated the use of statistical and machine learning methods for bark beetle detection. @lausch2013forecasting used hyperspectral airborne data HyMap to study early detection of bark beetle infestation with a limited amount of success. In the study by @lausch2013forecasting, single and multi-date Landsat data were successfully utilized to study forest disturbance by bark beetle.

There have only been limited studies assessing the effect of bark beetle green attack stage on plant biophysical and biochemical properties. Study by @abdullah2018european showed that there is a significant difference on leaf chlorophyll and nitrogen contents between healthy and infested trees during the green attack stage. This study also concluded that spectral responses (using in-situ data) between healthy and infested trees were significantly different. Work by @abdullah2019sentinel concluded that leaf chlorophyll and water content of healthy plants were significantly higher than infested trees at the green attack stage. They found dry matter content to be significantly higher for infested trees than healthy trees. A recent study by @ali2021canopy for the first time demonstrated the use of canopy chlorophyll content time series data retrieved from multispectral remote sensing data using the INFORM RTM for bark beetle infestation detection.
