# Discussion

This section discusses the results, limitations, improvements and a potential follow-up study.

## Artificial Neural Networks for predicting plant traits

This study showed that, given enough hidden layers and neurons, artificial neural networks can efficiently deal with high multi-collinearity that exists in hyperspectral remote sensing data. This study also showed the applicability of deep neural networks to predict plant biophysical and biochemical parameters. For all the INFORM parameters, the NN that was trained with simulated 231 PRISMA bands had better results compared to the NN that was trained with 5 principal components capturing most of the variation in the original data set. Training deep neural networks with full simulated image bands to predict plant biophysical and biochemical parameters that have effect within the whole spectra (e.g. LAI) could specifically be beneficial. However, it should also be noted that, depending on the availability of the computational resources and time, using a dimensionality reduction technique such as PCA may be preferred. This is because training NN with hundreds of predictors (e.g. hyperspectral image bands) usually needs more time to run compared to a PCA based NN that is trained with only a few or several predictors (principal components). However, in this study, for the NN that was trained with hyperspectral image bands it took less than 1200 epochs to converge, while the PCA based NN needed to run more than 2000 epochs. This could potentially indicate that for the NN it may be easier to learn the relationships between the plant traits and simulated spectra when all the bands are available. The design of the NN had a significant effect on the results and predictions. Neural networks with simpler architecture led to poor performance, while relatively deeper NN architecture had good prediction accuracies for the plant parameters.

## Limitations

It is important to note that, in this research all the data analysis, simulation and machine learning model training were done using a personal computer, which is not designed for time-consuming scientific simulations, machine learning model training and prediction. Having an access to a more advanced and high performance computer that are usually used for scientific research would significantly improve the simulation and training efficiency. This could also help assessing the impacts of different (e.g more complex) neural network architecture designs. Having an access to a better computer would also help try out different machine learning algorithms that require higher computational power such as gaussian process regression. It is highly recommended to use Keras and Tensorflow deep learning frameworks on a GPU as opposed to CPU [@allaire2018deep]. However, in this study a computer with the required GPU was not available and the training of the ML model was conducted using CPU. Otherwise, this could have improved the training efficiency further.

Another important limitation of this study is unavailability of the ground truth data. This means that, the trained model could not be validated against the ground truth data due to unavailable ground truth data during the time this research was conducted.

It is also important to mention that, all the synthetic training data (training set) was produced based on the typical values the spruce trees show for the chose plant variables. However, the trained model was applied to the whole study area which also contains other tree species. This was done due to inaccessible GIS data (e.g. polygon) that accurately separates European spruce trees from other tree species in the forest.

## Future perspectives

The model that was built with the help of the INFORM RTM and ANN can now be used to predict the plant traits $C_{ab}$, $C_{w}$, $C_{m}$ and $LAI_{s}$ in the hyperspectral remote sensing data PRISMA. These plant traits could be very beneficial to study forest disturbances especially for Spruce trees.

Potential follow up study could be to use this model in order to retrieve forest biochemical and biophysical maps from the hyperspectral data PRISMA for multiple dates. Then, scientific techniques like change detection could be applied to assess the change of these variables between multiple years. For this, many different time-series analysis techniques can be used to better understand the effect of the bark beetle and drought within the study area through time.

The follow-up time-series study based on biophysical and biochemical maps does not have to be limited to the PRISMA data. As all the scripts that were written to develop this model is publicly available on the GitHub repository of the author, few modifications can be made to build a new model for any other remote sensing image bands.

It is also important to mention that this model could still be improved further. For example, using destructive and non-destructive in-situ data for RTM simulations could potentially lead to better results. In this study, these types of data were not available and the referenced literature was used to choose the range of values for RTM simulation. This data could also help assess the performance of the models (RTM and ANN) in more detail.

In this study, only ANN ML model was used. Other machine learning models could also be trained for predicting plant traits. ANN mainly focuses on predicting the plant variables as closely as possible. However, it would also be very useful to assess the uncertainty available within the predictions of the machine learning model. For example, the Gaussian process regression method would be used to retrieve plant traits and also produce data that shows the amount of uncertainties that is available within the predicted maps. However this method is computationally very expensive and may not efficiently work on large amount of training data.

Another technique that could potentially be utilized is active learning (AL). AL techniques can be specifically useful for ML algorithms that demand siginificant amount of computational power to be trained on large amount of training data. AL can help choose the most important training samples that are available in the simulated training data [@verrelst2016active]. For example, AL methods can be combined with kernel based ML algorithms, such as Gaussian process regression.
