# Conclusion

In this research, radiative transfer models PROSPECT5, 4SAIL and FLIM were coupled to simulate forest canopy reflectance for the National Park Hunsruck-Hochwald. The simulated data was used to train ANN and the trained optimal and final ANN was used to predict forest biophysical and biochemical parameters on the PRISMA image of the study area.

Two ANN models were trained, one with a dimensionality reduction technique PCA and one without reducing the dimension of the hyperspectral data. In general, both of the trained NN models were found to perform well. However, the ANN that utilized all the available bands were found to be superior in terms of minimized cost function and prediction errors for each plant parameter. Specifically, prediction of the parameter $LAI_{s}$ resulted in noticeably higher accuracy when DR technique was not applied.

The NN model that was trained with the 231 simulated PRISMA bands, was chosen as the optimal model and used for the final predictions. This model achieved MSE of 0.07670474 and MAE of 0.13 on the testing data set. The plant parameter $C_{ab}$ was predicted with an $R^2$ of 0.89 and RMSE of 4.064 ($\frac{\mu g}{cm^2}$). $C_{w}$ was predicted with an $R^2$ of 0.94 and RMSE of 0.003 ($\frac{g}{cm^2}$). $R^2$ and RMSE values for $C_{m}$ were 0.95 and 0.002 ($\frac{g}{cm^2}$) respectively. Finally, $R^2$ and RMSE values for $LAI_{s}$ were 0.95 and 0.44 ($\frac{m^2}{m^2}$), respectively.

Reliability of the model on the real data could be checked with the help of destructive and non-destructive in-situ data for specifically spruce trees. At the time of this study, there was no data that specifically shows spruce trees while masking the other species, the model was applied to the whole image that does not only contain spruce trees. These types of data would help assess how well the model is working on the real imagery that contain spectral information of spruce trees in the National Park Hunsruck-Hochwald.

One of the main objectives of this study was to apply more recent sub-models of INFORM (PROSPECT5, 4SAIL and FLIM) which was met. Another main objective of this study was to use the simulated data, using an updated version of INFORM in order to train ANN model and let the model learn the relationship between the chosen plant traits and spectral bands. We also assessed whether the ANN model can deal with the multi-collinearity problem typically found in hyperspectral remote sensing data. We showed that, given enough hidden units and layers, ANN can efficiently deal with the multi-collinearity problem to predict the plant traits without using a DR technique. Finally, forest biophysical and biochemical maps for the study area Hunsrück-Hochwald were retrieved using the trained optimal ANN model.