# Hybrid Machine Learning Method {#hml}

Hybrid machine learning method is the combination of physically based RTMs ([Chapter 3](#rtm)) and MLRAs ([Chapter 4](#mlra)). The main idea behind this technique is to make use of the advantages of the two different methods at the same time. RTMs ([Chapter 2](#rtm)) can provide simulated data based on well-known and approved physical laws. Therefore, the data provided by RTMs can be applicable universally. Machine learning methods ([Chapter 4](#ml)) provide opportunities to efficiently deal with non-linear data (without making assumptions) in a reasonable time frame [@abdelbaki2021comparison; @de2020quantifying; @berger2021survey; @ke2016estimating]. Study by @fernandez2021hybrid mentions three main advantages of using the hybrid method to other techniques: better generalization of the model, better estimation of the biophysical parameters and finally, more efficient computation.

A typical procedure of using hybrid machine learning method to retrieve plant biophysical variables involves simulating coupled leaf and canopy models (e.g. PROSAIL) and store the simulated data in the so-called look-up-table (LUT). LUT typically stores simulated reflectance data and wide range of plant parameters. Once the LUT is available, a ML model can be trained using all the information available in the LUT as a training data set [@verrelst2019quantifying].

There have been large number of studies utilizing hybrid machine learning method for retrieval of plant traits. For example, a recent study by @cesar2021exploring combines PROSAIL ([Chapter 3.2](#sail)) and widely used MLRAs ([Chapter 4](#mlra)) with the hybrid approach in order to retrieve plant parameters from Sentinel-2 satellite data. In this study, performance of each MLRAs combined with PROSAIL was assessed when noise was added. In the study by @wei2017estimation plant LAI was successfully estimated using random forest regression and PROSAIL in a hybrid work flow. @verrelst2016active used hybrid RTM and kernel based machine learning techniques to estimate plant leaf area index and chlorophyll content. This study included the active learning (AL) technique for efficient retrieval strategy.