# Discussion

In this study, first the RTM model INFORM was used to simulate forest canopy reflectance and then, the simulated data was used to train ANN model in order for it to predict the studied plant traits of the hyperspectral remote sensing imagery. This section discusses the results and further improvements.

## Artificial Neural Networks for predicting plant traits

This study showed that, given enough hidden layers and neurons, using artificial neural networks can efficiently deal with high multi-collinearity that exist within hyperspectral remote sensing data to predict plant biophysical and biochemical parameters. For all the INFORM parameters the NN that was trained with simulated 231 PRISMA bands had better results compared to the NN that was trained with 5PCs. Training NN with full image bands to predict plant biophysical and biochemical parameters that have effect within the whole spectra (e.g. LAI) could specifically be beneficial. However, it should also be noted that, depending on the availability of the computational resources and time, using a dimensionality reduction technique such as PCA may be preferred. This is because training NN with hundreds of predictors (e.g. hyperspectral image bands) usually needs more time to run compared to a PCA based NN that is trained with only several predictors (principal components). However, in this study, for the NN that was trained with hyperspectral image bands it took less than 1200 epochs to converge, while the PCA based NN needed to run more than 2000 epochs. This could potentially indicate that for the NN it may be easier to learn the relationships between the plant traits and simulated spectra when all the bands are available. The design of the NN had a significant effect on the results and predictions. Neural networks with simpler architecture led to poor performance, while relatively deeper NN architecture had good prediction accuracies for the plant parameters.

## Further improvements

This model, that was built with the help of RTM and machine learning, can be used to predict the plant traits $C_{ab}$, $C_{w}$, $C_{m}$ and $LAI_{s}$ in the hyperspectral remote sensing data PRISMA. These plant traits could be very beneficial to study forest disturbances especially for Spruce trees.

Potential follow up study could be to use this model in order to retrieve forest biochemical and biophysical maps from the hyperspectral data PRISMA for multiple dates. Then, scientific techniques like change detection could be applied to assess the change of these variables between multiple years.

It is also important to mention that this model could still be improved further. For example, using destructive and non-destructive in-situ data for RTM simulations could potentially lead to better results. In this study, these types of data were not available and the referenced literature was used to choose the range of values for RTM simulation. This data could also help assess the performance of the models (RTM and ANN) in more detail.

In this study, only ANN model was used. Other machine learning models could also be trained for predicting plant traits. ANN mainly focuses on predicting the plant variables as closely as possible. However, it would also be very useful to assess the uncertainty within the predictions of the machine learning model. For example, the Gaussian process regression method would be used to retrieve plant traits and also produce data that shows the amount of uncertainties that is available within the predicted maps. However this method is computationally very expensive and may not efficiently work on large amount of training data.

Another technique that could potentially be utilized is active learning (AL). AL techniques can be specifically useful for ML algorithms that demand siginificant amount of computational power to be trained on large amount of training data. AL can help choose the most important training samples that are available in the simulated training data [@verrelst2016active]. For example, AL methods can be combined with kerbel based ML algorithms, such as Gaussian process regression.
